### ISSUE TITLE
KeyError when looking for engine version

### ISSUE THREAD

**Issue by r0mainK** [src-d/ml#200]
Last release we switched from a static definition of the VERSION param of `EngineDefault` class in `utils/engine` to a dynamic one, doing: 
`VERSION = {pkg.key: pkg.version for pkg in pip.get_installed_distributions()}["sourced-engine"]`

The problem is that when using spark in standalone mode, since we zip `sourced-engine`package it is not possible to get version info through `pip`, which raises the following error:

```
apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/python/pyspark/worker.py", line 166, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/opt/spark/python/pyspark/worker.py", line 55, in read_command
    command = serializer._read_with_length(file)
  File "/opt/spark/python/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/opt/spark/python/pyspark/serializers.py", line 451, in loads
    return pickle.loads(obj, encoding=encoding)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/pip-build-ynmrc1i8/sourced-ml/sourced/ml/transformers/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/pip-build-ynmrc1i8/sourced-ml/sourced/ml/transformers/basic.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/pip-build-ynmrc1i8/sourced-ml/sourced/ml/transformers/transformer.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/pip-build-ynmrc1i8/sourced-ml/sourced/ml/utils/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/sourced/ml/utils/engine.py", line 3, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.4/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'
```

In order to get rid of this we can simply revert back to the static def, and add a TODO to update it.

**Comment by r0mainK** [comment]
Apparently should be fixed by bumping pip version, will close when it disappears

**Comment by zurk** [comment]
yes, it is because pip 9.0.2, 9.0.3 should work well.

**Comment by zurk** [comment]
fix https://github.com/src-d/ml/pull/202

**Comment by zurk** [comment]
@r0mainK it should work now with a current master branch. Please try and close the issue if everything is fine.

**Comment by r0mainK** [comment]
Sure, will test it as soon as the job running on `local-gpu` finishes and close this.

**Comment by r0mainK** [comment]
Forgot about this, did not see this error since the update, closing
