### ISSUE TITLE
repos2bow fails if --docfreq points to a file in non-existing directory

### ISSUE THREAD

**Issue by smola** [src-d/ml#210]
Running: `srcml repos2bow --repositories ~/dev/working/siva-good --bow data/BOW --feature lit --languages Java  --docfreq data/docfreq --persist MEMORY_AND_DISK`

Directory `data` did not exist. The job failed pretty late with:

```
INFO:repos2bow:Writing docfreq to data/docfreq                                  
INFO:docfreq:Ordering the keys...
Traceback (most recent call last):
  File "ENV/bin/srcml", line 11, in <module>
    load_entry_point('sourced-ml', 'console_scripts', 'srcml')()
  File "/home/smola/dev/go/src/github.com/src-d/ml/sourced/ml/__main__.py", line 187, in main
    return handler(args)
  File "/home/smola/dev/go/src/github.com/src-d/ml/sourced/ml/cmd_entries/repos2bow.py", line 80, in repos2bow_entry
    return repos2bow_entry_template(args)
  File "/home/smola/dev/go/src/github.com/src-d/ml/sourced/ml/utils/engine.py", line 73, in wrapped_pause
    return func(cmdline_args, *args, **kwargs)
  File "/home/smola/dev/go/src/github.com/src-d/ml/sourced/ml/cmd_entries/repos2bow.py", line 68, in repos2bow_entry_template
    .save(args.docfreq)
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/site-packages/modelforge/model.py", line 269, in save
    self._write_tree(tree, output)
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/site-packages/modelforge/model.py", line 285, in _write_tree
    asdf.AsdfFile(final_tree).write_to(output, all_array_compression=ARRAY_COMPRESSION)
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/site-packages/asdf/asdf.py", line 890, in write_to
    with generic_io.get_file(fd, mode='w') as fd:
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/site-packages/asdf/generic_io.py", line 1186, in get_file
    fd = atomicfile.atomic_open(realpath, realmode)
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/site-packages/asdf/extern/atomicfile.py", line 139, in atomic_open
    delete=False)
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/tempfile.py", line 549, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/smola/dev/go/src/github.com/src-d/ml/ENV/lib/python3.6/tempfile.py", line 260, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'data/.___atomic_write25q7n3vo'
```

I would expect that `srcml` fails before starting the job if `data` does not exist, or that `data` is created automatically when saving the model.

**Comment by zurk** [comment]
Fix in the PR.
We should wait for @vmarkovtsev (till Monday I think) to review and merge.

**Comment by bzz** [comment]
Shall we closing the issue, as #211 seems to be merged now?

**Comment by zurk** [comment]
Actually not, because we just close it and move PR to modelforge: https://github.com/src-d/modelforge/pull/21 it is still pending.
